### ISSUE TITLE
CDN Request

### ISSUE THREAD

**Issue by kiky1991** [xiaoluoboding/vue-smart-widget#35]
Hi did u have CDN version ? or how to do it if i have to manually

**Comment by xiaoluoboding** [comment]
@kiky1991

you could use CDN service, like jsdelivr、unpkg or skypack

eg:

* jsdelivr version: https://www.jsdelivr.com/package/npm/vue-smart-widget
* skypack version: https://www.skypack.dev/view/vue-smart-widget

**Comment by kiky1991** [comment]
Hi, I get some example how to use vue smart widget using CDN ?
I got error message module not found
