### ISSUE TITLE
Full Demo?

### ISSUE THREAD

**Issue by conor-f** [xiaoluoboding/vue-smart-widget#39]
I would love to see the code for the demo website if possible? I cannot get similar results in Vue 3 at all.

https://xiaoluoboding.github.io/vue-smart-widget/#/widget-with-grid

This is the example I've been trying to work off.

**Comment by xiaoluoboding** [comment]
Vue 3 Version in the next branch

https://github.com/xiaoluoboding/vue-smart-widget/tree/next/examples
