### ISSUE TITLE
get null when `import {SmartWidget, SmartWidgetGrid}`

### ISSUE THREAD

**Issue by scil** [xiaoluoboding/vue-smart-widget#40]
I do not want to reg component globally. I only want both locally, but failed, because SmartWidget and SmartWidgeGrid are null.

Maybe you con include `src` in npm package

```
import Vue from 'vue'
// import VueSmartWidget from 'vue-smart-widget'  
import {SmartWidget, SmartWidgetGrid} from 'vue-smart-widget'

export default {
  name: "dashboard",
  components: {
    'smart-widget':SmartWidget,
    'smart-widget-grid':SmartWidgetGrid,
  },
  data () {
    return {
      layout: [
        { x: 0, y: 0, w: 4, h: 4, i: '0' },
        { x: 4, y: 0, w: 4, h: 4, i: '1' },
        { x: 8, y: 0, w: 4, h: 4, i: '2' }
      ]
    }
  } 
}

```

**Comment by DimaKuznietsov** [comment]
Do you use last version of vue? Could you also provide mistake from the console of browser

**Comment by scil** [comment]
I used vue2.

**Comment by drengr** [comment]
@scil I'm sorry for bothering you, but could you please tell me how did you solve this issue? Is there a way to have both components locally?

**Comment by drengr** [comment]
@scil I'm sorry for bothering you, but could you please tell me how did you solve this issue? Is there a way to have both components locally?
