### ISSUE TITLE
Can't resize smart-widget in smart-widget-layout

### ISSUE THREAD

**Issue by DimaKuznietsov** [xiaoluoboding/vue-smart-widget#45]
Can't resize smart-widget in smart-widget-layout. I can't even see the sign of the resize func

**Comment by DimaKuznietsov** [comment]
![image](https://user-images.githubusercontent.com/104508127/168607363-d37b3948-8a4f-4170-9015-5b03236c971f.png)

**Comment by xiaoluoboding** [comment]
@DimaKuznietsov Please provide the version of your env.

* version of vue
* version of vue-smart-widget

**Comment by DimaKuznietsov** [comment]
Vue: 3.2.13
Vue-smart-widget; 1.0.0-alpha.1

**Comment by DimaKuznietsov** [comment]
Fix with change version
