### ISSUE TITLE
resize 时，colNum 数量不会更新

### ISSUE THREAD

**Issue by mukiwu** [xiaoluoboding/vue-smart-widget#50]
透过 vue tools 可以看到 `<SmartWidgetGrid>` 里面还有包一个 `<GridLayout>` 组件
而我拖拽改变 grid 大小时，`<SmartWidgetGrid>` 的 `colNum` 会更新
![截图 2022-09-14 17 11 08](https://user-images.githubusercontent.com/3794103/190113133-8daca4fd-d753-44e3-bfa7-6d8e960d2e90.png)

但里面的 `<GridLayout>` 没有跟着更新
![截图 2022-09-14 17 11 13](https://user-images.githubusercontent.com/3794103/190113158-3ca6259d-a3ce-47b7-a219-3b5b28236d5f.png)

希望能在 grid-layout.vue 里面加上监听，即时更新 `colNum` 数据

**Comment by xiaoluoboding** [comment]
FIxed in #51
